"""add company scoped unique constraints

Revision ID: 0af424f1b914
Revises: 126337e9f170
Create Date: 2026-10-02 15:40:32.867076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0af424f1b914'
down_revision: Union[str, Sequence[str], None] = '126337e9f170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_sites_company_code', 'sites', ['company_id', 'code'])
    op.create_unique_constraint('uq_users_company_username', 'users', ['company_id', 'username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_company_username', 'users', type_='unique')
    op.drop_constraint('uq_sites_company_code', 'sites', type_='unique')
    # ### end Alembic commands ###
