"""add inventory schema

Revision ID: 1bd3bb02871a
Revises: 0af424f1b914
Create Date: 2026-10-02 16:28:31.283685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bd3bb02871a'
down_revision: Union[str, Sequence[str], None] = '0af424f1b914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('software',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=150), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('origem', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_software_identifier'), 'software', ['identifier'], unique=True)
    op.create_index(op.f('ix_software_tipo'), 'software', ['tipo'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('hostname', sa.String(length=150), nullable=False),
    sa.Column('loja', sa.String(length=100), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('mac', sa.String(length=17), nullable=True),
    sa.Column('sistema', sa.String(length=100), nullable=True),
    sa.Column('versao', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('processador', sa.String(length=255), nullable=True),
    sa.Column('ram_total', sa.String(length=50), nullable=True),
    sa.Column('disco_total', sa.String(length=50), nullable=True),
    sa.Column('disco_usado', sa.String(length=50), nullable=True),
    sa.Column('disco_livre', sa.String(length=50), nullable=True),
    sa.Column('disco_percentual', sa.Integer(), nullable=True),
    sa.Column('rustdesk_id', sa.String(length=100), nullable=True),
    sa.Column('data_coleta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_company_id'), 'devices', ['company_id'], unique=False)
    op.create_index(op.f('ix_devices_hostname'), 'devices', ['hostname'], unique=False)
    op.create_index(op.f('ix_devices_ip'), 'devices', ['ip'], unique=False)
    op.create_index(op.f('ix_devices_mac'), 'devices', ['mac'], unique=False)
    op.create_index(op.f('ix_devices_rustdesk_id'), 'devices', ['rustdesk_id'], unique=False)
    op.create_index(op.f('ix_devices_site_id'), 'devices', ['site_id'], unique=False)
    op.create_table('site_identifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'identifier', name='uq_site_identifier_company_identifier')
    )
    op.create_index(op.f('ix_site_identifiers_company_id'), 'site_identifiers', ['company_id'], unique=False)
    op.create_index(op.f('ix_site_identifiers_identifier'), 'site_identifiers', ['identifier'], unique=False)
    op.create_index(op.f('ix_site_identifiers_site_id'), 'site_identifiers', ['site_id'], unique=False)
    op.create_table('device_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('campo', sa.String(length=100), nullable=False),
    sa.Column('valor_anterior', sa.String(length=1000), nullable=True),
    sa.Column('valor_novo', sa.String(length=1000), nullable=True),
    sa.Column('data_alteracao', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_history_campo'), 'device_history', ['campo'], unique=False)
    op.create_index(op.f('ix_device_history_data_alteracao'), 'device_history', ['data_alteracao'], unique=False)
    op.create_index(op.f('ix_device_history_device_id'), 'device_history', ['device_id'], unique=False)
    op.create_table('device_software',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('software_id', sa.Integer(), nullable=False),
    sa.Column('installed', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'software_id', name='uq_device_software')
    )
    op.create_index(op.f('ix_device_software_device_id'), 'device_software', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_software_software_id'), 'device_software', ['software_id'], unique=False)
    op.create_table('software_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_software_id', sa.Integer(), nullable=False),
    sa.Column('pacote', sa.String(length=255), nullable=False),
    sa.Column('versao_anterior', sa.String(length=255), nullable=True),
    sa.Column('versao_nova', sa.String(length=255), nullable=True),
    sa.Column('data_alteracao', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_software_id'], ['device_software.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_software_history_data_alteracao'), 'software_history', ['data_alteracao'], unique=False)
    op.create_index(op.f('ix_software_history_device_software_id'), 'software_history', ['device_software_id'], unique=False)
    op.create_table('software_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_software_id', sa.Integer(), nullable=False),
    sa.Column('pacote', sa.String(length=255), nullable=False),
    sa.Column('versao', sa.String(length=255), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_software_id'], ['device_software.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_software_id', 'pacote', name='uq_device_software_package')
    )
    op.create_index(op.f('ix_software_packages_device_software_id'), 'software_packages', ['device_software_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_software_packages_device_software_id'), table_name='software_packages')
    op.drop_table('software_packages')
    op.drop_index(op.f('ix_software_history_device_software_id'), table_name='software_history')
    op.drop_index(op.f('ix_software_history_data_alteracao'), table_name='software_history')
    op.drop_table('software_history')
    op.drop_index(op.f('ix_device_software_software_id'), table_name='device_software')
    op.drop_index(op.f('ix_device_software_device_id'), table_name='device_software')
    op.drop_table('device_software')
    op.drop_index(op.f('ix_device_history_device_id'), table_name='device_history')
    op.drop_index(op.f('ix_device_history_data_alteracao'), table_name='device_history')
    op.drop_index(op.f('ix_device_history_campo'), table_name='device_history')
    op.drop_table('device_history')
    op.drop_index(op.f('ix_site_identifiers_site_id'), table_name='site_identifiers')
    op.drop_index(op.f('ix_site_identifiers_identifier'), table_name='site_identifiers')
    op.drop_index(op.f('ix_site_identifiers_company_id'), table_name='site_identifiers')
    op.drop_table('site_identifiers')
    op.drop_index(op.f('ix_devices_site_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_rustdesk_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_mac'), table_name='devices')
    op.drop_index(op.f('ix_devices_ip'), table_name='devices')
    op.drop_index(op.f('ix_devices_hostname'), table_name='devices')
    op.drop_index(op.f('ix_devices_company_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_software_tipo'), table_name='software')
    op.drop_index(op.f('ix_software_identifier'), table_name='software')
    op.drop_table('software')
    # ### end Alembic commands ###
