"""add company to software

Revision ID: 4e5d3f229fe4
Revises: 1bd3bb02871a
Create Date: 2026-10-02 18:52:40.048678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e5d3f229fe4'
down_revision: Union[str, Sequence[str], None] = '1bd3bb02871a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('software', sa.Column('company_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_software_identifier'), table_name='software')
    op.create_index(op.f('ix_software_identifier'), 'software', ['identifier'], unique=False)
    op.create_index(op.f('ix_software_company_id'), 'software', ['company_id'], unique=False)
    op.create_unique_constraint('uq_software_company_identifier', 'software', ['company_id', 'identifier'])
    op.create_foreign_key(None, 'software', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'software', type_='foreignkey')
    op.drop_constraint('uq_software_company_identifier', 'software', type_='unique')
    op.drop_index(op.f('ix_software_company_id'), table_name='software')
    op.drop_index(op.f('ix_software_identifier'), table_name='software')
    op.create_index(op.f('ix_software_identifier'), 'software', ['identifier'], unique=True)
    op.drop_column('software', 'company_id')
    # ### end Alembic commands ###
