"""add_ad_configs_and_user_auth_fields

Revision ID: 4f92d620e39c
Revises: 8cb9957661b1
Create Date: 2026-10-03 15:36:42.866486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f92d620e39c'
down_revision: Union[str, Sequence[str], None] = '8cb9957661b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('server_host', sa.String(length=255), nullable=False),
    sa.Column('server_port', sa.Integer(), nullable=False),
    sa.Column('use_ssl', sa.Boolean(), nullable=False),
    sa.Column('use_tls', sa.Boolean(), nullable=False),
    sa.Column('domain', sa.String(length=150), nullable=False),
    sa.Column('base_dn', sa.String(length=255), nullable=False),
    sa.Column('bind_user', sa.String(length=255), nullable=True),
    sa.Column('bind_password', sa.String(length=255), nullable=True),
    sa.Column('user_search_filter', sa.String(length=255), nullable=False),
    sa.Column('superadmin_groups', sa.JSON(), nullable=False),
    sa.Column('group_mappings', sa.JSON(), nullable=False),
    sa.Column('default_role_id', sa.Integer(), nullable=True),
    sa.Column('auto_sync_on_login', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['default_role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_configs_company_id'), 'ad_configs', ['company_id'], unique=False)
    op.add_column('users', sa.Column('auth_source', sa.String(length=50), server_default='local', nullable=False))
    op.add_column('users', sa.Column('ad_dn', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('ad_guid', sa.String(length=100), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'ad_guid')
    op.drop_column('users', 'ad_dn')
    op.drop_column('users', 'auth_source')
    op.drop_index(op.f('ix_ad_configs_company_id'), table_name='ad_configs')
    op.drop_table('ad_configs')
    # ### end Alembic commands ###
